services:
  scylla:
    public: true
    build:
      context: .
    scale: 1
    ports:
      - 8080
    volumes:
      - scylla_data:/data/python

volumes:
  scylla_data:
    driver_opts:
      size: 128Mi